### ISSUE TITLE
rescue on namespaced error class

### ISSUE THREAD

**Issue by jjgreen** [purcell/ruby-hash-syntax#6]
I get an incorrect toggling (forward) for rescue on a namespaced error class:

    rescue Activity::IngestError => err

becomes

    rescue Activity:IngestError: err

which is a syntax error of course.

**Comment by jjgreen** [comment]
Thanks for the rapid fix!  (Great script BTW, has saved me a load of time.)

**Comment by purcell** [comment]
Cool, glad it's been useful to you.
