### ISSUE TITLE
Removes preceeding character

### ISSUE THREAD

**Issue by J3RN** [purcell/ruby-hash-syntax#8]
Hi there! I've been having an issue wherein `M-x ruby-toggle-hash-syntax` is removing whatever character is before the first symbol in the hash. For instance,
```ruby
has_many :foos, :dependent => :destroy
```
when selected with `M-x ruby-toggle-hash-syntax` run becomes
```ruby
has_man :foos,dependent: :destroy
```

Similarly, when working with a hash with curly braces, this
```ruby
{:foo => :bar}
```
becomes
```ruby
foo: :bar}
```

Emacs version: `GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))`
ruby-mode version: `1.2`

**Comment by J3RN** [comment]
Thanks a ton! :smiley:

**Comment by akimd** [comment]
Please, update the version on melpa.

**Comment by purcell** [comment]
> Please, update the version on melpa.

MELPA is always up to date, so I guess you mean MELPA Stable? If so, I've just pushed a new version tag, so MELPA Stable should update soon.
